const config = {
    maxSizeOfMobileVersion: 900,
    desktopLinks: [
        {name: 'Hospital', link: "/hospital"},
        {name: 'Pharmacy', link: "/pharmacy"},
        {name: 'Laboratory', link: "/laboratory"},
        {name: 'Suppliers', link: "/suppliers"},
    ],
    mobileMenuLinks: [
        {name: "Hospital", link: "/hospital", icon: "local_hospital"},
        {name: "Pharmacy", link: "/pharmacy", icon: "medication"},
        {name: "Laboratory", link: "/laboratory", icon: "science"},
        {name: "Suppliers", link: "/suppliers", icon: "store"},
        {name: "Contact", link: "/contact", icon: "phone"}
    ],
    hospitalProducts: [
        {
            name: "Product no 1",
            id: 0,
            description: "In today's digital world, technology is transforming the way we live, work, and communicate. Every year, new innovations emerge, from artificial intelligence to biotechnology, enhancing various aspects of life. As individuals and companies adapt, digital literacy becomes essential, influencing fields like education, healthcare, and finance. For example, online learning platforms have made education accessible, allowing students worldwide to gain knowledge without geographical restrictions. Similarly, telemedicine is revolutionizing healthcare, enabling remote consultations and efficient diagnoses. However, with these advancements come challenges, including data security and privacy. Organizations are investing heavily in cybersecurity to protect user information, but cyber threats continue to evolve, posing significant risks. Despite these challenges, the benefits of technological progress are evident, fostering global collaboration and driving economic growth. Moving forward, sustainable innovation and ethical considerations will be key to harnessing technology’s potential while addressing environmental and societal impacts. Ultimately, the future promises continued growth, but with responsibility.",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: true,
        },
        {
            name: "Product no 2",
            id: 1,
            description: "Product no 2 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: true,
        },
        {
            name: "Product no 3",
            id: 2,
            description: "Product no 3 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 4",
            id: 3,
            description: "Product no 4 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 5",
            id: 4,
            description: "Product no 5 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 6",
            id: 5,
            description: "Product no 6 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 7",
            id: 6,
            description: "Product no 7 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 8",
            id: 7,
            description: "Product no 8 description",
            category: 'Category 2',
            dataOfAppearance: '30.10.2023',
            disabled: false,
        },
        {
            name: "Product no 9",
            id: 8,
            description: "Product no 9 description",
            category: 'Category 2',
            dataOfAppearance: '30.09.2024',
            disabled: false,
        },
    ],
    pharmacyProducts: [
        {
            name: "Product no 1",
            id: 0,
            description: "In today's digital world, technology is transforming the way we live, work, and communicate. Every year, new innovations emerge, from artificial intelligence to biotechnology, enhancing various aspects of life. As individuals and companies adapt, digital literacy becomes essential, influencing fields like education, healthcare, and finance. For example, online learning platforms have made education accessible, allowing students worldwide to gain knowledge without geographical restrictions. Similarly, telemedicine is revolutionizing healthcare, enabling remote consultations and efficient diagnoses. However, with these advancements come challenges, including data security and privacy. Organizations are investing heavily in cybersecurity to protect user information, but cyber threats continue to evolve, posing significant risks. Despite these challenges, the benefits of technological progress are evident, fostering global collaboration and driving economic growth. Moving forward, sustainable innovation and ethical considerations will be key to harnessing technology’s potential while addressing environmental and societal impacts. Ultimately, the future promises continued growth, but with responsibility.",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 2",
            id: 1,
            description: "Product no 2 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 3",
            id: 2,
            description: "Product no 3 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 4",
            id: 3,
            description: "Product no 4 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 5",
            id: 4,
            description: "Product no 5 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 6",
            id: 5,
            description: "Product no 6 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 7",
            id: 6,
            description: "Product no 7 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 8",
            id: 7,
            description: "Product no 8 description",
            category: 'Category 2',
            dataOfAppearance: '30.10.2023',
            disabled: false,
        },
        {
            name: "Product no 9",
            id: 8,
            description: "Product no 9 description",
            category: 'Category 2',
            dataOfAppearance: '30.09.2024',
            disabled: false,
        },
    ],
    laboratoryProducts: [
        {
            name: "Product no 1",
            id: 0,
            description: "In today's digital world, technology is transforming the way we live, work, and communicate. Every year, new innovations emerge, from artificial intelligence to biotechnology, enhancing various aspects of life. As individuals and companies adapt, digital literacy becomes essential, influencing fields like education, healthcare, and finance. For example, online learning platforms have made education accessible, allowing students worldwide to gain knowledge without geographical restrictions. Similarly, telemedicine is revolutionizing healthcare, enabling remote consultations and efficient diagnoses. However, with these advancements come challenges, including data security and privacy. Organizations are investing heavily in cybersecurity to protect user information, but cyber threats continue to evolve, posing significant risks. Despite these challenges, the benefits of technological progress are evident, fostering global collaboration and driving economic growth. Moving forward, sustainable innovation and ethical considerations will be key to harnessing technology’s potential while addressing environmental and societal impacts. Ultimately, the future promises continued growth, but with responsibility.",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 2",
            id: 1,
            description: "Product no 2 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 3",
            id: 2,
            description: "Product no 3 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 4",
            id: 3,
            description: "Product no 4 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 5",
            id: 4,
            description: "Product no 5 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 6",
            id: 5,
            description: "Product no 6 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 7",
            id: 6,
            description: "Product no 7 description",
            category: 'Category 1',
            dataOfAppearance: '30.10.2024',
            disabled: false,
        },
        {
            name: "Product no 8",
            id: 7,
            description: "Product no 8 description",
            category: 'Category 2',
            dataOfAppearance: '30.10.2023',
            disabled: false,
        },
        {
            name: "Product no 9",
            id: 8,
            description: "Product no 9 description",
            category: 'Category 2',
            dataOfAppearance: '30.09.2024',
            disabled: false,
        },
    ],
    suppliers: [
        {
            name: "Best supplier nr. 1",
            id: 0,
            description: 'Best suppliers description',
            pdfExists: true,
            disabled: false,
        },
        {
            name: "Best supplier nr. 2",
            id: 0,
            description: 'Best suppliers description',
            pdfExists: false,
            disabled: false,
        },
        {
            name: "Best supplier nr. 3",
            id: 0,
            description: 'Best suppliers description',
            pdfExists: false,
            disabled: false,
        }
    ]
};

export default config